Assigment 0

Anna Monso Rodriguez 

A20653296

CS-584

Fall semester

PART A: Vector Operations

In [22]:
# Definitions 

p = [2, -1, 4]
q = [0, 3,  5]
r = [1, -2, 2]

#1.  3p + 2q
res1 = [0]*len(p)
for i in range(len(p)):
    res1[i]=3*p[i]+2*q[i]
print("3p + 2q =", res1)

3p + 2q = [6, 3, 22]


In [23]:
#2. p a unit vector in the direction of p
# module of p
import math 
mod_p = math.sqrt(sum([x**2 for x in p]))
p_res = [x/mod_p for x in p]
print("p2, a unit vector in the direction of p =", p_res)

p2, a unit vector in the direction of p = [0.4364357804719848, -0.2182178902359924, 0.8728715609439696]


In [24]:
#3. module of p and the angle of p relative to the positive y-axis 
import numpy as np
print("module of p =", mod_p)

y = np.array([0, 1, 0])
mod_y = math.sqrt(sum([x**2 for x in y]))
cos_p = np.dot(p,y)/(mod_p*mod_y)
angle_p = math.acos(cos_p)
print("angle of p with y-axis ", angle_p)

module of p = 4.58257569495584
angle of p with y-axis  1.790784304190356


In [25]:
# 4. Direction of the cosines of p 
cos_p = [x/mod_p for x in p]
print("Direction of the cosines of p", cos_p)

Direction of the cosines of p [0.4364357804719848, -0.2182178902359924, 0.8728715609439696]


In [28]:
# 5. The angle between p and q
mod_q = math.sqrt(sum([x**2 for x in q]))
cos_pq = np.dot(p,q)/(mod_p*mod_q)
angle_pq = math.acos(cos_pq)
print("Angle between p and q", angle_pq)

Angle between p and q 0.8812217608851565


In [29]:
# 6. p·q and q·p 
pq = np.dot(p,q)
qp = np.dot(q,p)
print("p · q = ", pq)
print("q · p = ", qp)

p · q =  17
q · p =  17


In [30]:
# 7. p · q using the angle between p and q 
pq = cos_pq*mod_p*mod_q
print("p · q = ", pq)

p · q =  17.0


In [31]:
# 8. The scalar projection of q onto p 
proj_q = pq/mod_p
print("Escalar projection of q onto p", proj_q)

Escalar projection of q onto p 3.709704134011871


In [33]:
# 9. A vector that is perpendicular to both p and q 
s = [0,4,1]
res = np.dot(p,s)
print("p and s are perpendicular, because the dot product is = ", res)

p and s are perpendicular, because the dot product is =  0


In [ ]:
# 10. p x q and q x p 
pq_cross = np.cross(p,q)
print("p x q ", pq_cross)

qp_cross = np.cross(q,p)
print("q x p ", qp_cross)

p x q  [-17 -10   6]
[17 10 -6]


In [ ]:
# 11. A vector perpendicular to both p and q 
# the cross product between p and q is perpendicular to both, we can prove it 

res1 = np.dot(p, pq_cross)
print("p and p x q are perpendicular res = ", res1)

In [37]:
# 12. The linear dependency between p,q, and r 
matrix = np.stack([p,q,r])
det = np.linalg.det(matrix)
if det==0:
    print("The determinant is equal to 0, meaning that are dependent")
else:
    print("The determinant is different to 0, meaning that are independent")

The determinant is different to 0, meaning that are independent


In [56]:
# 13. pTq
p = np.array([2, -1, 4])  
q = np.array([0, 3, 5])
res = np.dot(p,q)
print(res)

p_col = p.reshape(-1,1)   # (3,1)
q_row = q.reshape(1,-1)   # (1,3)

pqT = p_col @ q_row       
print(pqT)


17
[[ 0  6 10]
 [ 0 -3 -5]
 [ 0 12 20]]


PART B: Matrix Operations



In [60]:
X = np.stack([[2,1,0],[-1,3,4],[3,2,-2]])
Y = np.stack([[4,-1,2],[3,0,-3],[1,2,1]])
Z = np.stack([[2,0,-1],[1,4,5],[3,1,2]])
s = np.array([-1,4,0])

In [62]:
# 1. X +2Y
res = X + 2*Y
res

array([[10, -1,  4],
       [ 5,  3, -2],
       [ 5,  6,  0]])

In [68]:
#2. XY and YX
XY = X@Y
print("result XY",XY)

YX = Y@X
print("result YX ",YX)

result XY [[11 -2  1]
 [ 9  9 -7]
 [16 -7 -2]]
result YX  [[15  5 -8]
 [-3 -3  6]
 [ 3  9  6]]


In [ ]:
#3. (XY)T and YtXt

print("XY transpose ", XYT)

YtXt = XYT
print("XtYt  ", XYT)

XY transpose  [[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]
XtYt   [[11  9 16]
 [-2  9 -7]
 [ 1 -7 -2]]


In [71]:
# 4. |X| and |Z| 
detX = np.linalg.det(X)
print("|X| ", detX)

detZ = np.linalg.det(Z)
print("|Z| ", detZ)


|X|  -17.999999999999996
|Z|  17.0


In [79]:
# 5. The matrix (either X, Y, or Z) in which the row vectors form an orthogonal set

def rows_are_orthogonal(M):
    rows = M.shape[0]
    for i in range(rows):
        for j in range(i+1, rows):
            if np.dot(M[i], M[j]) != 0:
                return False
    return True

if rows_are_orthogonal(X):
    print("X is orthogonal")
else: 
    print("X is not orthogonal")
    
if rows_are_orthogonal(Y):
    print("Y is orthogonal")
else: 
    print("Y is not orthogonal")
    
if rows_are_orthogonal(Z):
    print("Z is orthogonal")
else: 
    print("Z is not orthogonal")

X is not orthogonal
Y is not orthogonal
Z is not orthogonal


In [ ]:
# 6/7. Xinv Yinv Zinv
Xinv = np.linalg.inv(X)
print("Xinv", Xinv)

Yinv = np.linalg.inv(Y)
print("Yinv", Yinv)

Zinv = np.linalg.inv(Z)
print("Zinv", Zinv)

Xinv [[ 0.77777778 -0.11111111 -0.22222222]
 [-0.55555556  0.22222222  0.44444444]
 [ 0.61111111  0.05555556 -0.38888889]]
Yinv [[ 0.14285714  0.11904762  0.07142857]
 [-0.14285714  0.04761905  0.42857143]
 [ 0.14285714 -0.21428571  0.07142857]]
Zinv [[ 0.17647059 -0.05882353  0.23529412]
 [ 0.76470588  0.41176471 -0.64705882]
 [-0.64705882 -0.11764706  0.47058824]]


In [ ]:
# 9. The product of Xs
X@s

array([ 2, 13,  5])

In [81]:
#10. The scalar projection of the rows of Xonto the vector s
modS = np.linalg.norm(s)
rowsX = X.shape[0]
res=[]
for i in range(rowsX):
    r=np.dot(X[i],s)
    res.append(r)
scalarproj=res/modS
print("The scalar projection is scalar projection is ", scalarproj)




The scalar projection is scalar projection is  [0.48507125 3.15296313 1.21267813]


In [105]:
# 10. The vector projection of the rows of X onto the vector s (with s normalized)
rowsX = X.shape[0]
k = (X @ s) / (s @ s)          
projections = k[:, None] * s   
print(projections)

[[-0.11764706  0.47058824  0.        ]
 [-0.76470588  3.05882353  0.        ]
 [-0.29411765  1.17647059  0.        ]]


In [ ]:
# 11. Linear combination of columns of X using the elements of s
c1 = X[:,0]
c2 = X[:,1]
c3 = X[:,2]
res = s[0]*c1 + s[1]*c2 + s[2]*c3
print("linear combination, ", res)

array([ 2, 13,  5])

In [89]:
# 12. Yt = s
t = Yinv@s 
print( "t is ", t)

t is  [ 0.33333333  0.33333333 -1.        ]


In [90]:
#13. Zt = s
t = Zinv@s
print("t is equal to ", t)

t is equal to  [-0.41176471  0.88235294  0.17647059]


PART C: Eigenvalues and Eigenvectors

In [92]:
M = np.stack([[3,2],[-1,4]])
N = np.stack([[5,-3],[-3,6]])
P = np.stack([[2,4],[4,8]])

In [104]:
# 1. Eigenvalues and eigenvectors of M 
eig = np.linalg.eig(M)
print("Eigenvlaues are, ",eig[0])
print("Eigenvectors are ", eig[1])


Eigenvlaues are,  [3.5+1.32287566j 3.5-1.32287566j]
Eigenvectors are  [[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415+0.54006172j 0.20412415-0.54006172j]]


In [ ]:
#2. The dot product between the eigenvectors of M

eigenvalues = eig[0]
res = np.dot(eigenvalues[0], eigenvalues[1])
print("the dot product between the eigenvectors of M is ", res)

the dot product between the eigenvectors of M is  (14+0j)


In [101]:
# 3. The dot product between the eigenvectors of N
eigN = np.linalg.eig(N)
eigenvaluesN = eigN[0]
res = np.dot(eigenvaluesN[0], eigenvaluesN[1])
print("the dot product between the eigenvectors of M is ", res)

the dot product between the eigenvectors of M is  20.999999999999996


In [ ]:
#4. Since the matrix N is symetric the eigenvalues are orthogonal 

In [103]:
# 5. Pt=0
t_trivial = np.zeros(2)
print("trivial solutions ", t_trivial)
U, S, VT = np.linalg.svd(P)
t_nontrivial = VT[-1]         
t1 = t_nontrivial / t_nontrivial[-1]  
t2 = -t1 
print("Non trivial solutions ", t1,t2)

trivial solutions  [0. 0.]
Non trivial solutions  [-2.  1.] [ 2. -1.]


In [ ]:
# 6. Mt=0
t_trivial = np.zeros(2)
print("trivial solutions ", t_trivial)
# It only has one solution because |M|=14 (different to 0) thus, is invertible and the null space contains only the zero vector